# Generated by Django 4.2 on 2023-04-20 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='super',
            old_name='super_types',
            new_name='super_type',
        ),
    ]
